site_name: STAR Informatics
site_url: https://starinformatics.github.io
repo_url: https://github.com/STARInformatics/starinformatics.github.io

nav:
    - Welcome to STAR Informatics:
        - Overview: index.md

extra_css:
  - stylesheets/extra.css

theme:
    name: "material"
    favicon: img/favicon.ico
    logo: img/star-informatics-tree.png
    icon:
        admonition:
        server: material/server
    language: en
    # Pick color: https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#primary-color
    palette:
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: light blue
          toggle:
              icon: material/weather-night
              name: Switch to dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: blue grey
          toggle:
              icon: material/weather-sunny
              name: Switch to light mode
    features:
        - navigation.indexes
        - navigation.footer
        - navigation.sections
        - navigation.top
        - navigation.tracking
        - content.code.copy
        - content.code.annotate
        - content.code.select
        - search.highlight
        - search.share
        - search.suggest
        - toc.follow

copyright: Copyright &copy; 2025 Delphinai Corporation

markdown_extensions:
    - admonition # Supported types: https://squidfunk.github.io/mkdocs-material/reference/admonitions/#supported-types
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.details
    - pymdownx.extra
    - abbr
    - pymdownx.snippets:
        auto_append:
            - docs/includes/abbreviations.md
    - attr_list
    - smarty

plugins:
    - search
    - autorefs
    - glightbox:
        touchNavigation: true
        loop: false
        effect: zoom
        slide_effect: slide
        width: 100%
        height: auto
        zoomable: true
        draggable: true
        auto_caption: false
        caption_position: bottom

extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/STARInformatics

watch:
    - docs
